### ISSUE TITLE
神舟飞船轨道舱的rcs不工作

### ISSUE THREAD

**Issue by vaporz** [Armo00/KIU-Pack#11]
ksp1.12.3版，组装了神舟飞船，也设置了燃料，实际发现服务舱的rcs能工作（按空格键激活主发动机以后），但轨道舱的rcs不工作。
经过测试发现，轨道舱在分级里是个“分离器”，按空格激活以后，轨道舱的rcs才被激活，但这时已经被分离了。
所以，“轨道舱是一个分离器”，这很奇怪啊。。。

**Comment by vaporz** [comment]
找到了一个可以不分离又能激活rcs喷口的方法——通过设置动作组。
虽然可以起作用，但现在这个样子还是怪怪的

**Comment by Armo00** [comment]
你是什么环境?

**Comment by vaporz** [comment]
RSS，RO

**Comment by Armo00** [comment]
> RSS，RO

在vab里面能提前打开么?我之前好像没有遇到过这种问题。

**Comment by vaporz** [comment]
在vab里好像没有那个菜单选项，没事，现在也能玩，感谢~
