### ISSUE TITLE
神舟飞船隔热大底不适配RO的问题以及当前的解决方案

### ISSUE THREAD

**Issue by KayJayQ** [Armo00/KIU-Pack#14]
rt，看到论坛里面有人提了一下。
修改 KIU/KIU_Chinese_Human_Spaceflight_pack/ShenZhou/Part/HeatShield.cfg
在41行后添加属性字段
heatShieldTag = Gemini
即可让RO加载此part
进入游戏后隔热底除了烧蚀剂外还显示空的Ch条可正常吸热

**Comment by Armo00** [comment]
已修复
