### ISSUE TITLE
神舟飞船载人舱的reaction wheel不工作

### ISSUE THREAD

**Issue by vaporz** [Armo00/KIU-Pack#28]
ksp版本1.12.3，安装最新版的RO。
在游戏场景里右键点载人舱，在“控制”下面只有rcs，没有sas的项目。
在编辑器界面里右键点载人舱，在模块功能描述里也没有“动量轮”这一项。

不只是载人舱，好像KIU的所有part在RO里都失去了“动量轮”功能。

**Comment by vaporz** [comment]
找到解决办法了，在每个part的配置文件里增加下面内容就可以兼容RO：
```
PART
{
	reactionWheelPowerDraw = 0.8
	reactionWheelMode = CMG
```
里面的0.8表示动量轮的功率是0.8KW，详细说明在这里：
https://github.com/KSP-RO/RealismOverhaul/blob/09255f536e07176af38d05fa3d249526e17e1461/GameData/RealismOverhaul/RO_ReactionWheels.cfg#L9

**Comment by vaporz** [comment]
发了一个PR，请review
#29

**Comment by Armo00** [comment]
我自己RO用得少，但我感觉是否不应当直接part本身的cfg里面去加内容，而应当单独写MM给RO加支持？

**Comment by vaporz** [comment]
> 单独写MM给RO加支持

这个我就不太会了。。

**Comment by Armo00** [comment]
我写了个patch更新到master分支了，你试试看拉一下最新的版本测试一下
包含梦天/问天实验舱。天和大柱段，神舟返回舱和轨道舱，梦舟返回舱，天宫和天舟的
