### ISSUE TITLE
在RSS/RO中，天和服务舱报Waterfall相关的错误

### ISSUE THREAD

**Issue by vaporz** [Armo00/KIU-Pack#30]
KIU版本：Version V1.0.8
如题，“天和服务舱”在RSS/RO环境中，会报大量如下错误：
 NullReferenceException: Object reference not set to an instance of an object
	Waterfall.AtmosphereDensityController.UpdateInternal () (at <08fdda801253440bb2ff6cf5ae754d1e>:0)
	Waterfall.WaterfallController.Update () (at <08fdda801253440bb2ff6cf5ae754d1e>:0)
	Waterfall.ModuleWaterfallFX.LateUpdate () (at <08fdda801253440bb2ff6cf5ae754d1e>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by Armo00** [comment]
我在RSS环境下无法复现这个问题，请提供完整的日志文件，以及复现的步骤。另外，RCS的特效是否是正常的呢？

**Comment by vaporz** [comment]
[debug.zip](https://github.com/user-attachments/files/17300788/debug.zip)

> RCS的特效是否是正常的呢？

见“debug.zip”中的截图，rcs看起来工作正常，但是主推进器没看到火焰效果，实际有燃料，throttle也开了，能听到发动机工作的声音，速度也在变化，但是看不到任何火光，应该就是这里出了问题。

复现步骤：
1，打开ksp，进入存档，进入vab。
2，新建一个只有“天和服务舱”的vessel，点“发射”。
3，进入flight scene，查看debug log，好多nullpointer，见log。

KSP Version 1.12.3，modlist见附件，不过我猜应该就是主发动机的特效配置问题。

**Comment by Armo00** [comment]
在RO环境下仍然无法复现你这个问题。log里面的报错是缺少了StockWaterfallEffects里面的stock-hypergolic-core模版。你这边可以尝试以下任意两种方案：

**Comment by vaporz** [comment]
@Armo00 非常感谢！用方案2解决了问题！
方案1不好使的原因是，我压根没装StockWaterfallEffect，因为CKAN提示RO跟这个mod冲突，虽然可以强行安装，但不知道会有什么负面影响。
![微信截图_20241009202252](https://github.com/user-attachments/assets/c298c61f-4ad9-49ea-b5f5-fc111ecac871)
![微信截图_20241009202600](https://github.com/user-attachments/assets/b935b15c-ae05-43b6-9f26-983809f41e62)
